name: ci
description: Installs dependencies

runs:
  using: composite
  steps:
    # Install Flutter SDK
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        architecture: x64

    # Get package dependencies and generate files
    - name: Get package dependencies and generate files
      shell: bash
      run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs

    # Get example app dependencies and generate files
    - name: Get example app dependencies and generate files
      shell: bash
      working-directory: example/wallet
      run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs

    # Get example app dependencies and generate files
    - name: Get example app dependencies and generate files
      shell: bash
      working-directory: example/dapp
      run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs

    - name: Verify formatting and analyze project source
      shell: bash
      run: dart format --output=none --set-exit-if-changed .

    # - name: Analyze project source
    #   shell: bash
    #   run: flutter analyze
    